version: "3.8"

services:
  lidarr:
    image: linuxserver/lidarr:latest
    depends_on:
      - prowlarr
      - torrents
      - vpn
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "8686:8686"
    restart: unless-stopped
    volumes:
      - ./lidarr/config:/config
      - ./data:/data
  plex:
    image: linuxserver/plex:latest
    environment:
      - PGID=1000
      - PUID=1000
      - VERSION=docker
    ports:
      - "32400:32400"
    restart: unless-stopped
    volumes:
      - ./plex/config:/config
      - ./data/media/movies:/movies
      - ./data/media/music:/music
      - ./data/media/tv:/tv
      - ./data/media/xxx:/xxx
  prowlarr:
    image: linuxserver/prowlarr:develop
    depends_on:
      - vpn
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "9696:9696"
    restart: unless-stopped
    volumes:
      - ./prowlarr/config:/config
  radarr:
    image: linuxserver/radarr:latest
    depends_on:
      - prowlarr
      - torrents
      - vpn
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "7878:7878" # radarr
    restart: unless-stopped
    volumes:
      - ./radarr/config:/config
      - ./data:/data
  readarr:
    image: linuxserver/readarr:develop
    depends_on:
      - prowlarr
      - torrents
      - vpn
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "8787:8787"
    restart: unless-stopped
    volumes:
      - ./readarr/config:/config
      - ./data:/data
  sonarr:
    image: linuxserver/sonarr:latest
    depends_on:
      - prowlarr
      - torrents
      - vpn
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "8989:8989"
    restart: unless-stopped
    volumes:
      - ./sonarr/config:/config
      - ./data:/data
  torrents:
    image: linuxserver/transmission:latest
    depends_on:
      - vpn
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    network_mode: "service:vpn"
    restart: unless-stopped
    volumes:
      - ./torrents/config:/config
      - ./data/downloads:/data/downloads
  torrents-webui:
    image: alpine/socat
    depends_on:
      - vpn
    command: "TCP-LISTEN:9091,fork,reuseaddr TCP:vpn:9091"
    networks:
      - vpn
    ports:
      - "9091:9091"
  vpn:
    container_name: vpn
    image: thrnz/docker-wireguard-pia:latest
    cap_add:
      - NET_ADMIN
    environment:
      LOC: mexico
      PASS_FILE: /config/pass
      USER_FILE: /config/user
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - vpn
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    volumes:
      - ./vpn/config:/config:ro
  whisparr:
    image: cr.hotio.dev/hotio/whisparr:nightly
    depends_on:
      - prowlarr
      - torrents
      - vpn
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "6969:6969"
    restart: unless-stopped
    volumes:
      - ./whisparr/config:/config
      - ./data:/data

networks:
  vpn:
