version: "3.7"

services:
  readarr:
    container_name: readarr
    image: cr.hotio.dev/hotio/readarr
    ports:
      - "8787:8787"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ./readarr/config:/config
  vpn:
    container_name: vpn
    image: thrnz/docker-wireguard-pia
    cap_add:
      - NET_ADMIN
    environment:
      LOC: mexico
      LOCAL_NETWORK: 192.168.10.0/24
      PASS_FILE: /config/pass
      USER_FILE: /config/user
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./vpn/config:/config:ro
