version: "3.8"

networks:
  vpn:

services:
  lidarr:
    image: linuxserver/lidarr:latest
    depends_on:
      - prowlarr
      - torrents
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "8686:8686"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./lidarr:/config
      - synology:/data
  overseerr:
    image: linuxserver/overseerr:latest
    depends_on:
#      - plex
      - radarr
      - sonarr
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "5055:5055"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./overseerr:/config
#  plex:
#    image: plexinc/pms-docker:latest
#    environment:
#      - PLEX_CLAIM=claim-pzyfwjps6coGEfuAxAMp
#      - PLEX_GID=1000
#      - PLEX_UID=1000
#      - TZ=US/Pacific
#    networks:
#      - vpn
#    ports:
#      - "32400:32400" # GUI
#      - "1900:1900/udp" # DLNA server
#      - "32469:32469/tcp" # DLNA server
#      - "8324:8324/tcp" # Roku
#      - "32410:32410/udp" # Plex to plex
#      - "32412:32412/udp" # Plex to plex
#      - "32413:32413/udp" # Plex to plex
#      - "32414:32414/udp" # Plex to plex
#    restart: unless-stopped
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ./plex:/config
#      - synology:/data
#      - synology-plex:/transcode
  prowlarr:
    image: linuxserver/prowlarr:develop
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "9696:9696"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prowlarr:/config
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    depends_on:
      - vpn
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    network_mode: "service:vpn"
    restart: unless-stopped
    volumes:
      - ./qbittorrent:/config
      - synology-downloads:/data/downloads
  qbittorrent-webui:
    image: alpine/socat
    depends_on:
      - qbittorrent
    command: "TCP-LISTEN:8080,fork,reuseaddr TCP:vpn:8080"
    networks:
      - vpn
    ports:
      - "8080:8080"
  radarr:
    image: linuxserver/radarr:latest
    depends_on:
      - prowlarr
      - torrents
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "7878:7878" # radarr
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr:/config
      - synology:/data
  readarr:
    image: linuxserver/readarr:develop
    depends_on:
      - prowlarr
      - torrents
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "8787:8787"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./readarr:/config
      - synology:/data
  recyclarr:
    image: recyclarr/recyclarr
    environment:
      - TZ=US/Pacific
    networks:
      - vpn
    user: 1000:1000
    volumes:
      - ./recyclarr:/config
  sonarr:
    image: linuxserver/sonarr:develop
    depends_on:
      - prowlarr
      - torrents
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "8989:8989"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr:/config
      - synology:/data
  stash:
    image: stashapp/stash:latest
    environment:
      - STASH_STASH=/data/media/xxx/
      - STASH_GENERATED=/stash/generated/
      - STASH_METADATA=/stash/metadata/
      - STASH_CACHE=/stash/cache/
      - STASH_PORT=9999
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    ports:
      - "9999:9999"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./stash:/root/.stash
      - synology:/data
      - synology-stash:/stash
  torrents:
    image: linuxserver/transmission:latest
    depends_on:
      - vpn
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    network_mode: "service:vpn"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./torrents:/config
      - synology-downloads:/data/downloads
  torrents-webui:
    image: alpine/socat
    depends_on:
      - torrents
    command: "TCP-LISTEN:9091,fork,reuseaddr TCP:vpn:9091"
    networks:
      - vpn
    ports:
      - "9091:9091"
  vpn:
    container_name: vpn
    image: thrnz/docker-wireguard-pia:latest
    cap_add:
      - NET_ADMIN
    environment:
      LOC: mexico
      PASS_FILE: /config/pass
      USER_FILE: /config/user
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - vpn
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./vpn:/config:ro
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  whisparr:
    image: cr.hotio.dev/hotio/whisparr:nightly
    depends_on:
      - prowlarr
      - torrents
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "6969:6969"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./whisparr:/config
      - synology:/data

volumes:
  synology:
    driver_opts:
      device: "//playastation/servarr"
      o: "addr=playastation,rw,username=servarr,password=6`V#M|Wx,file_mode=0777,dir_mode=0777"
      type: "cifs"
  synology-downloads:
    driver_opts:
      device: "//playastation/servarr/downloads"
      o: "addr=playastation,rw,username=servarr,password=6`V#M|Wx,file_mode=0777,dir_mode=0777"
      type: "cifs"
  synology-plex:
    driver_opts:
      device: "//playastation/servarr/plex"
      o: "addr=playastation,rw,username=servarr,password=6`V#M|Wx,file_mode=0777,dir_mode=0777"
      type: "cifs"
  synology-stash:
    driver_opts:
      device: "//playastation/servarr/stash"
      o: "addr=playastation,rw,username=servarr,password=6`V#M|Wx,file_mode=0777,dir_mode=0777"
      type: "cifs"
