version: "3.7"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    network_mode: "service:vpn"
    volumes:
      - ./prowlarr/config:/config
  readarr:
    container_name: readarr
    image: cr.hotio.dev/hotio/readarr
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    network_mode: "service:vpn"
    volumes:
      - ./readarr/config:/config
      - ./torrents/downloads:/downloads
  torrents:
    image: linuxserver/transmission
    container_name: torrents
    depends_on:
      - vpn
    environment:
      - PUID=00002
      - PGID=00002
      - TZ="US/Pacific"
    network_mode: "service:vpn"
    volumes:
      - ./torrents/config:/config
      - ./torrents/downloads:/downloads
  vpn:
    container_name: vpn
    image: thrnz/docker-wireguard-pia
    cap_add:
      - NET_ADMIN
    environment:
      LOC: mexico
      LOCAL_NETWORK: 192.168.10.0/24
      PASS_FILE: /config/pass
      USER_FILE: /config/user
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 8787:8787 # readarr
      - 9091:9091 # torrents
      - 9696:9696 # prowlarr
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./vpn/config:/config:ro
