version: "3.8"

networks:
  vpn:

services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    volumes:
      - ./jellyfish:/config
      - synology:/data
    ports:
      - "8096:8096"
    restart: unless-stopped
  lidarr:
    image: linuxserver/lidarr:latest
    depends_on:
      - prowlarr
      - torrents
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "8686:8686"
    restart: unless-stopped
    volumes:
      - ./lidarr:/config
      - synology:/data
  overseerr:
    image: linuxserver/overseerr:latest
    depends_on:
      - plex
      - radarr
      - sonarr
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "5055:5055"
    restart: unless-stopped
    volumes:
      - ./overseerr:/config
  plex:
    image: linuxserver/plex:latest
    environment:
      - PGID=1000
      - PUID=1000
      - VERSION=docker
    networks:
      - vpn
    ports:
      - "32400:32400"
    restart: unless-stopped
    volumes:
      - ./plex:/config
      - synology:/data
  prowlarr:
    image: linuxserver/prowlarr:develop
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "9696:9696"
    restart: unless-stopped
    volumes:
      - ./prowlarr:/config
  radarr:
    image: linuxserver/radarr:latest
    depends_on:
      - prowlarr
      - torrents
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "7878:7878" # radarr
    restart: unless-stopped
    volumes:
      - ./radarr:/config
      - synology:/data
  readarr:
    image: linuxserver/readarr:develop
    depends_on:
      - prowlarr
      - torrents
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "8787:8787"
    restart: unless-stopped
    volumes:
      - ./readarr:/config
      - synology:/data
  sonarr:
    image: linuxserver/sonarr:latest
    depends_on:
      - prowlarr
      - torrents
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "8989:8989"
    restart: unless-stopped
    volumes:
      - ./sonarr:/config
      - synology:/data
  torrents:
    image: linuxserver/transmission:latest
    depends_on:
      - vpn
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    network_mode: "service:vpn"
    restart: unless-stopped
    volumes:
      - ./torrents:/config
      - synology-downloads:/downloads
  torrents-webui:
    image: alpine/socat
    depends_on:
      - torrents
    command: "TCP-LISTEN:9091,fork,reuseaddr TCP:vpn:9091"
    networks:
      - vpn
    ports:
      - "9091:9091"
  vpn:
    container_name: vpn
    image: thrnz/docker-wireguard-pia:latest
    cap_add:
      - NET_ADMIN
    environment:
      LOC: mexico
      PASS_FILE: /config/pass
      USER_FILE: /config/user
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - vpn
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    volumes:
      - ./vpn:/config:ro
  whisparr:
    image: cr.hotio.dev/hotio/whisparr:nightly
    depends_on:
      - prowlarr
      - torrents
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=US/Pacific
    networks:
      - vpn
    ports:
      - "6969:6969"
    restart: unless-stopped
    volumes:
      - ./whisparr:/config
      - synology:/data

volumes:
  synology:
    driver_opts:
      device: "//playastation/servarr"
      o: "addr=playastation,rw,username=servarr,password=6`V#M|Wx,file_mode=0777,dir_mode=0777"
      type: "cifs"
  synology-downloads:
    driver_opts:
      device: "//playastation/servarr/downloads"
      o: "addr=playastation,rw,username=servarr,password=6`V#M|Wx,file_mode=0777,dir_mode=0777"
      type: "cifs"
