version: "3.7"

services:
  prowlarr:
    image: linuxserver/prowlarr:develop
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    network_mode: "service:vpn"
    restart: unless-stopped
    volumes:
      - ./prowlarr/config:/config
  radarr:
    image: linuxserver/radarr:latest
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    network_mode: "service:vpn"
    restart: unless-stopped
    volumes:
      - ./radarr/config:/config
      - ./data/media/movies:/movies
      - ./data/downloads:/downloads
  readarr:
    image: linuxserver/readarr:develop
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    network_mode: "service:vpn"
    restart: unless-stopped
    volumes:
      - ./readarr/config:/config
      - ./data/media/books:/books
      - ./data/downloads:/downloads
  sonarr:
    image: linuxserver/sonarr:latest
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    network_mode: "service:vpn"
    restart: unless-stopped
    volumes:
      - ./sonarr/config:/config
      - ./data/media/tv:/tv
      - ./data/downloads:/downloads
  torrents:
    image: linuxserver/transmission:latest
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    network_mode: "service:vpn"
    restart: unless-stopped
    volumes:
      - ./torrents/config:/config
      - ./data/downloads:/downloads
  vpn:
    container_name: vpn
    image: thrnz/docker-wireguard-pia:latest
    cap_add:
      - NET_ADMIN
    environment:
      LOC: mexico
      LOCAL_NETWORK: 192.168.10.0/24
      PASS_FILE: /config/pass
      USER_FILE: /config/user
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 7878:7878 # radarr
      - 8787:8787 # readarr
      - 8989:8989 # sonarr
      - 9091:9091 # torrents
      - 9696:9696 # prowlarr
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    volumes:
      - ./vpn/config:/config:ro
