###################################################################################################
# Recyclarr Configuration Template: Anime Radarr                                                  #
# Updated: 2023-10-07                                                                             #
# Documentation: https://recyclarr.dev                                                            #
# Note: If you are using multiple profiles in a single instance, please read the following        #
# documentation about file merging:                                                               #
# https://recyclarr.dev/wiki/yaml/config-examples/#merge-single-instance                          #
###################################################################################################

# Instance Definition: https://recyclarr.dev/wiki/yaml/config-reference/basic/
radarr:
  radarr:
    base_url: http://radarr:7878
    api_key: b3c466ac67084b8689e8a4cdb53e34c8

    include:
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime

    # Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
          - a5d148168c4506b55cf53984107c396e # 10bit
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired
