###################################################################################################
# Recyclarr Configuration Template: Anime Radarr                                                  #
# Updated: 2023-10-07                                                                             #
# Documentation: https://recyclarr.dev                                                            #
# Note: If you are using multiple profiles in a single instance, please read the following        #
# documentation about file merging:                                                               #
# https://recyclarr.dev/wiki/yaml/config-examples/#merge-single-instance                          #
###################################################################################################

# Instance Definition: https://recyclarr.dev/wiki/yaml/config-reference/basic/
radarr:
  radarr:
    base_url: http://radarr:7878
    api_key: b3c466ac67084b8689e8a4cdb53e34c8

    # Media Naming Configuration
    media_naming:
      folder: plex
      movie:
        rename: true
        standard: default

    include:
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime

    quality_profiles:
      - name: Any
        upgrade:
          allowed: true
          until_quality: Bluray-2160p
        qualities:
          - name: Bluray-2160p
          - name: WEBDL-2160p
          - name: WEBRip-2160p
          - name: Bluray-1080p
          - name: WEBDL-1080p
          - name: WEBRip-1080p
          - name: Bluray-720p
          - name: WEBDL-720p
          - name: WEBRip-720p
          - name: HDTV-2160p
          - name: HDTV-1080p
          - name: HDTV-720p

    custom_formats:
      # Anime
      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
          - a5d148168c4506b55cf53984107c396e # 10bit
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      # Movie Versions
      - trash_ids:
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
          - 9c38ebb7384dada637be8899efa68e6f # SDR
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
          - 0a3f082873eb454bde444150b70253cc # Extras
          - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
          - b17886cb4158d9fea189859409975758 # HDR10+ Boost
          - 2899d84dc9372de3408e6d8cc18e9666 # x264
        quality_profiles:
          - name: Any
