###################################################################################################
# Recyclarr Configuration Template: Anime Sonarr                                                  #
# Updated: 2023-10-07                                                                             #
# Documentation: https://recyclarr.dev                                                            #
# Note: If you are using multiple profiles in a single instance, please read the following        #
# documentation about file merging:                                                               #
# https://recyclarr.dev/wiki/yaml/config-examples/#merge-single-instance                          #
# This config file is for use with Sonarr V4 only                                                 #
###################################################################################################

# Instance Definition: https://recyclarr.dev/wiki/yaml/config-reference/basic/
sonarr:
  sonarr-v4:
    base_url: http://sonarr:8989
    api_key: 189c2276d7aa4710a9df07192102db11

    include:
      - template: sonarr-quality-definition-anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p

    quality_profiles:
      - name: WEB-2160p
        reset_unmatched_scores:
          except:
            - 'Language: Not Original'
        qualities:
          - name: WEB 2160p
            qualities:
              - WEBDL-2160p
              - WEBRip-2160p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
          - name: Bluray
            qualities:
              - Bluray-1080p
              - Bluray-720p
          - name: HDTV
            qualities:
              - HDTV-1080p
              - HDTV-720p

    # Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      # HDR Formats
      - trash_ids:
          # Comment out the next line if you and all of your users' setups are fully DV compatible
          - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)
          # HDR10Plus Boost - Uncomment the next line if any of your devices DO support HDR10+
          # - 0dad0a507451acddd754fe6dc3a7f5e7 # HDR10Plus Boost
          - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
        quality_profiles:
          - name: WEB-2160p
